export type PropertiesSearchFiltersState = {
  listingType: string;
  setListingType: (value: string) => void;
  category: string;
  setCategory: (value: string) => void;
  propertyType: string;
  setPropertyType: (value: string) => void;
  minPrice: string;
  setMinPrice: (value: string) => void;
  maxPrice: string;
  setMaxPrice: (value: string) => void;
  bedrooms: string;
  setBedrooms: (value: string) => void;
  city: string;
  setCity: (value: string) => void;
  locality: string;
  setLocality: (value: string) => void;
  furnishing: string;
  setFurnishing: (value: string) => void;
  freshOnly: boolean;
  setFreshOnly: (value: boolean) => void;
  verifiedOnly: boolean;
  setVerifiedOnly: (value: boolean) => void;
  readyToVisitOnly: boolean;
  setReadyToVisitOnly: (value: boolean) => void;
  ownerListedOnly: boolean;
  setOwnerListedOnly: (value: boolean) => void;
  budgetMatchOnly: boolean;
  applyQuickFilter: (action: string) => void;
  setPage: (page: number | ((prev: number) => number)) => void;
  clearFilters: () => void;
};
